# written by tode --shortcut-setup — frees the chords the editor needs from kitty
map cmd+=
map shift+cmd+=
map cmd+-
map shift+cmd+-
map cmd+0
map ctrl+shift+`
map ctrl+tab
map ctrl+shift+tab
map ctrl+shift+q
map cmd+w close_tab
map cmd+up
map cmd+down
map cmd+f
map cmd+enter
map cmd+n
map cmd+r
map cmd+1
map cmd+3
map cmd+5
map cmd+9
map shift+cmd+]
map shift+cmd+[
map shift+cmd+i
map opt+cmd+s
map cmd+,
map opt+cmd+r
map cmd+l
map cmd+d
map ctrl+shift+d launch --location=vsplit --cwd=current
map cmd+left
map cmd+right
map shift+cmd+left
map shift+cmd+right
